/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SummitRouteImport } from './routes/summit'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedClaimTicketRouteImport } from './routes/_authenticated.claim-ticket'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AttendeeCodeRouteImport } from './routes/attendee.$code'
import { Route as CheckInVirtualRouteImport } from './routes/check-in.virtual'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterIdRouteImport } from './routes/register.$id'
import { Route as TicketCodeRouteImport } from './routes/ticket.$code'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminCheckInRouteImport } from './routes/_authenticated.admin.check-in'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated.admin.emails'
import { Route as AuthenticatedAdminNetworkingRouteImport } from './routes/_authenticated.admin.networking'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated.admin.registrations'
import { Route as AuthenticatedAdminVirtualRouteImport } from './routes/_authenticated.admin.virtual'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated.admin.whatsapp'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated.profile.index'
import { Route as AuthenticatedProfileAgendaRouteImport } from './routes/_authenticated.profile.agenda'
import { Route as AuthenticatedProfileHackathonRouteImport } from './routes/_authenticated.profile.hackathon'
import { Route as AuthenticatedProfileNetworkRouteImport } from './routes/_authenticated.profile.network'
import { Route as AuthenticatedProfilePaymentsRouteImport } from './routes/_authenticated.profile.payments'
import { Route as AuthenticatedProfileSettingsRouteImport } from './routes/_authenticated.profile.settings'
import { Route as AuthenticatedProfileTicketRouteImport } from './routes/_authenticated.profile.ticket'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SummitRoute = SummitRouteImport.update({
  id: '/summit',
  path: '/summit',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClaimTicketRoute =
  AuthenticatedClaimTicketRouteImport.update({
    id: '/claim-ticket',
    path: '/claim-ticket',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeCodeRoute = AttendeeCodeRouteImport.update({
  id: '/attendee/$code',
  path: '/attendee/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInVirtualRoute = CheckInVirtualRouteImport.update({
  id: '/check-in/virtual',
  path: '/check-in/virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIdRoute = RegisterIdRouteImport.update({
  id: '/register/$id',
  path: '/register/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCodeRoute = TicketCodeRouteImport.update({
  id: '/ticket/$code',
  path: '/ticket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCheckInRoute =
  AuthenticatedAdminCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNetworkingRoute =
  AuthenticatedAdminNetworkingRouteImport.update({
    id: '/networking',
    path: '/networking',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVirtualRoute =
  AuthenticatedAdminVirtualRouteImport.update({
    id: '/virtual',
    path: '/virtual',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileAgendaRoute =
  AuthenticatedProfileAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileHackathonRoute =
  AuthenticatedProfileHackathonRouteImport.update({
    id: '/hackathon',
    path: '/hackathon',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileNetworkRoute =
  AuthenticatedProfileNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePaymentsRoute =
  AuthenticatedProfilePaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileSettingsRoute =
  AuthenticatedProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileTicketRoute =
  AuthenticatedProfileTicketRouteImport.update({
    id: '/ticket',
    path: '/ticket',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/network': typeof NetworkRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/summit': typeof SummitRoute
  '/tracks': typeof TracksRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/claim-ticket': typeof AuthenticatedClaimTicketRoute
  '/admin/login': typeof AdminLoginRoute
  '/attendee/$code': typeof AttendeeCodeRoute
  '/check-in/virtual': typeof CheckInVirtualRoute
  '/register/$id': typeof RegisterIdRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/check-in': typeof AuthenticatedAdminCheckInRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/networking': typeof AuthenticatedAdminNetworkingRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/virtual': typeof AuthenticatedAdminVirtualRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/profile/agenda': typeof AuthenticatedProfileAgendaRoute
  '/profile/hackathon': typeof AuthenticatedProfileHackathonRoute
  '/profile/network': typeof AuthenticatedProfileNetworkRoute
  '/profile/payments': typeof AuthenticatedProfilePaymentsRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/profile/ticket': typeof AuthenticatedProfileTicketRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/network': typeof NetworkRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/summit': typeof SummitRoute
  '/tracks': typeof TracksRoute
  '/claim-ticket': typeof AuthenticatedClaimTicketRoute
  '/admin/login': typeof AdminLoginRoute
  '/attendee/$code': typeof AttendeeCodeRoute
  '/check-in/virtual': typeof CheckInVirtualRoute
  '/register/$id': typeof RegisterIdRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/register': typeof RegisterIndexRoute
  '/admin/check-in': typeof AuthenticatedAdminCheckInRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/networking': typeof AuthenticatedAdminNetworkingRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/virtual': typeof AuthenticatedAdminVirtualRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/profile/agenda': typeof AuthenticatedProfileAgendaRoute
  '/profile/hackathon': typeof AuthenticatedProfileHackathonRoute
  '/profile/network': typeof AuthenticatedProfileNetworkRoute
  '/profile/payments': typeof AuthenticatedProfilePaymentsRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/profile/ticket': typeof AuthenticatedProfileTicketRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/network': typeof NetworkRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/signup': typeof SignupRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/summit': typeof SummitRoute
  '/tracks': typeof TracksRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/claim-ticket': typeof AuthenticatedClaimTicketRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/attendee/$code': typeof AttendeeCodeRoute
  '/check-in/virtual': typeof CheckInVirtualRoute
  '/register/$id': typeof RegisterIdRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/admin/check-in': typeof AuthenticatedAdminCheckInRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/networking': typeof AuthenticatedAdminNetworkingRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/virtual': typeof AuthenticatedAdminVirtualRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/profile/agenda': typeof AuthenticatedProfileAgendaRoute
  '/_authenticated/profile/hackathon': typeof AuthenticatedProfileHackathonRoute
  '/_authenticated/profile/network': typeof AuthenticatedProfileNetworkRoute
  '/_authenticated/profile/payments': typeof AuthenticatedProfilePaymentsRoute
  '/_authenticated/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/_authenticated/profile/ticket': typeof AuthenticatedProfileTicketRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agenda'
    | '/contact'
    | '/login'
    | '/merch'
    | '/network'
    | '/profile'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/speakers'
    | '/sponsors'
    | '/summit'
    | '/tracks'
    | '/admin'
    | '/claim-ticket'
    | '/admin/login'
    | '/attendee/$code'
    | '/check-in/virtual'
    | '/register/$id'
    | '/ticket/$code'
    | '/register/'
    | '/admin/check-in'
    | '/admin/emails'
    | '/admin/networking'
    | '/admin/registrations'
    | '/admin/virtual'
    | '/admin/whatsapp'
    | '/profile/agenda'
    | '/profile/hackathon'
    | '/profile/network'
    | '/profile/payments'
    | '/profile/settings'
    | '/profile/ticket'
    | '/admin/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agenda'
    | '/contact'
    | '/login'
    | '/merch'
    | '/network'
    | '/profile'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/speakers'
    | '/sponsors'
    | '/summit'
    | '/tracks'
    | '/claim-ticket'
    | '/admin/login'
    | '/attendee/$code'
    | '/check-in/virtual'
    | '/register/$id'
    | '/ticket/$code'
    | '/register'
    | '/admin/check-in'
    | '/admin/emails'
    | '/admin/networking'
    | '/admin/registrations'
    | '/admin/virtual'
    | '/admin/whatsapp'
    | '/profile/agenda'
    | '/profile/hackathon'
    | '/profile/network'
    | '/profile/payments'
    | '/profile/settings'
    | '/profile/ticket'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/agenda'
    | '/contact'
    | '/login'
    | '/merch'
    | '/network'
    | '/profile'
    | '/reset-password'
    | '/schedule'
    | '/signup'
    | '/speakers'
    | '/sponsors'
    | '/summit'
    | '/tracks'
    | '/_authenticated/admin'
    | '/_authenticated/claim-ticket'
    | '/_authenticated/profile'
    | '/admin/login'
    | '/attendee/$code'
    | '/check-in/virtual'
    | '/register/$id'
    | '/ticket/$code'
    | '/register/'
    | '/_authenticated/admin/check-in'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/networking'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/virtual'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/profile/agenda'
    | '/_authenticated/profile/hackathon'
    | '/_authenticated/profile/network'
    | '/_authenticated/profile/payments'
    | '/_authenticated/profile/settings'
    | '/_authenticated/profile/ticket'
    | '/_authenticated/admin/'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgendaRoute: typeof AgendaRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  NetworkRoute: typeof NetworkRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SignupRoute: typeof SignupRoute
  SpeakersRoute: typeof SpeakersRoute
  SponsorsRoute: typeof SponsorsRoute
  SummitRoute: typeof SummitRoute
  TracksRoute: typeof TracksRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AttendeeCodeRoute: typeof AttendeeCodeRoute
  CheckInVirtualRoute: typeof CheckInVirtualRoute
  RegisterIdRoute: typeof RegisterIdRoute
  TicketCodeRoute: typeof TicketCodeRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summit': {
      id: '/summit'
      path: '/summit'
      fullPath: '/summit'
      preLoaderRoute: typeof SummitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/claim-ticket': {
      id: '/_authenticated/claim-ticket'
      path: '/claim-ticket'
      fullPath: '/claim-ticket'
      preLoaderRoute: typeof AuthenticatedClaimTicketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendee/$code': {
      id: '/attendee/$code'
      path: '/attendee/$code'
      fullPath: '/attendee/$code'
      preLoaderRoute: typeof AttendeeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/virtual': {
      id: '/check-in/virtual'
      path: '/check-in/virtual'
      fullPath: '/check-in/virtual'
      preLoaderRoute: typeof CheckInVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$id': {
      id: '/register/$id'
      path: '/register/$id'
      fullPath: '/register/$id'
      preLoaderRoute: typeof RegisterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$code': {
      id: '/ticket/$code'
      path: '/ticket/$code'
      fullPath: '/ticket/$code'
      preLoaderRoute: typeof TicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/check-in': {
      id: '/_authenticated/admin/check-in'
      path: '/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AuthenticatedAdminCheckInRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/networking': {
      id: '/_authenticated/admin/networking'
      path: '/networking'
      fullPath: '/admin/networking'
      preLoaderRoute: typeof AuthenticatedAdminNetworkingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/virtual': {
      id: '/_authenticated/admin/virtual'
      path: '/virtual'
      fullPath: '/admin/virtual'
      preLoaderRoute: typeof AuthenticatedAdminVirtualRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/agenda': {
      id: '/_authenticated/profile/agenda'
      path: '/agenda'
      fullPath: '/profile/agenda'
      preLoaderRoute: typeof AuthenticatedProfileAgendaRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/hackathon': {
      id: '/_authenticated/profile/hackathon'
      path: '/hackathon'
      fullPath: '/profile/hackathon'
      preLoaderRoute: typeof AuthenticatedProfileHackathonRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/network': {
      id: '/_authenticated/profile/network'
      path: '/network'
      fullPath: '/profile/network'
      preLoaderRoute: typeof AuthenticatedProfileNetworkRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/payments': {
      id: '/_authenticated/profile/payments'
      path: '/payments'
      fullPath: '/profile/payments'
      preLoaderRoute: typeof AuthenticatedProfilePaymentsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/settings': {
      id: '/_authenticated/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AuthenticatedProfileSettingsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/ticket': {
      id: '/_authenticated/profile/ticket'
      path: '/ticket'
      fullPath: '/profile/ticket'
      preLoaderRoute: typeof AuthenticatedProfileTicketRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCheckInRoute: typeof AuthenticatedAdminCheckInRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminNetworkingRoute: typeof AuthenticatedAdminNetworkingRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminVirtualRoute: typeof AuthenticatedAdminVirtualRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCheckInRoute: AuthenticatedAdminCheckInRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminNetworkingRoute: AuthenticatedAdminNetworkingRoute,
  AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
  AuthenticatedAdminVirtualRoute: AuthenticatedAdminVirtualRoute,
  AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileAgendaRoute: typeof AuthenticatedProfileAgendaRoute
  AuthenticatedProfileHackathonRoute: typeof AuthenticatedProfileHackathonRoute
  AuthenticatedProfileNetworkRoute: typeof AuthenticatedProfileNetworkRoute
  AuthenticatedProfilePaymentsRoute: typeof AuthenticatedProfilePaymentsRoute
  AuthenticatedProfileSettingsRoute: typeof AuthenticatedProfileSettingsRoute
  AuthenticatedProfileTicketRoute: typeof AuthenticatedProfileTicketRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileAgendaRoute: AuthenticatedProfileAgendaRoute,
  AuthenticatedProfileHackathonRoute: AuthenticatedProfileHackathonRoute,
  AuthenticatedProfileNetworkRoute: AuthenticatedProfileNetworkRoute,
  AuthenticatedProfilePaymentsRoute: AuthenticatedProfilePaymentsRoute,
  AuthenticatedProfileSettingsRoute: AuthenticatedProfileSettingsRoute,
  AuthenticatedProfileTicketRoute: AuthenticatedProfileTicketRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClaimTicketRoute: typeof AuthenticatedClaimTicketRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClaimTicketRoute: AuthenticatedClaimTicketRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AgendaRoute: AgendaRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  NetworkRoute: NetworkRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SignupRoute: SignupRoute,
  SpeakersRoute: SpeakersRoute,
  SponsorsRoute: SponsorsRoute,
  SummitRoute: SummitRoute,
  TracksRoute: TracksRoute,
  AdminLoginRoute: AdminLoginRoute,
  AttendeeCodeRoute: AttendeeCodeRoute,
  CheckInVirtualRoute: CheckInVirtualRoute,
  RegisterIdRoute: RegisterIdRoute,
  TicketCodeRoute: TicketCodeRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
