// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function decodeJWT(token: string) {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) throw new Error('Invalid JWT format');

    let base64 = parts[1];
    base64 = base64.replace(/-/g, '+').replace(/_/g, '/');
    base64 += '='.repeat((4 - (base64.length % 4)) % 4);

    const payloadStr = Buffer.from(base64, 'base64').toString('utf8');
    return JSON.parse(payloadStr);
  } catch (e) {
    throw new Error('Invalid token');
  }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const request = getRequest();
    const authHeader = request?.headers?.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header');
    }

    const bearerMatch = authHeader.match(/^Bearer\s+(.+)$/);
    if (!bearerMatch) {
      throw new Error('Unauthorized: Invalid authorization header');
    }

    const token = bearerMatch[1];
    const payload = decodeJWT(token);
    const userId = payload.sub;

    if (!userId) {
      throw new Error('Unauthorized: Invalid token');
    }

    return next({
      context: {
        userId,
        token,
      },
    });
  },
);
