// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iipxtvptxjqwjxkayxar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcHh0dnB0eGpxd2p4a2F5eGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0OTk3MjksImV4cCI6MjA5NTA3NTcyOX0.c92dq7E88msuR721fA56zi2I3VDURGzdNaVBj3P9SxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});