// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azfxehiwkmuvoksulswr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6ZnhlaGl3a211dm9rc3Vsc3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NzYwOTksImV4cCI6MjA5NTA1MjA5OX0.XfAuu5m3nRnBBH4E1NZWgw1Xn_r0f4y9NFS3dj0o9cM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});